# backend_lab2
Реализованы CRUD-операции для пользователя и пользовательское исключение NullArgumentException, унаследованное от Exception

В местах, где может выпасть исключение, находятся try-catch блоки<br>
Программа проходит все тесты, не прерывается
